DROP DATABASE IF EXISTS twiggs_reviews;
CREATE DATABASE twiggs_reviews;

\c twiggs_reviews

CREATE SCHEMA user_services;

SET search_path TO user_services,public;
	
CREATE TABLE media(
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	media_name varchar(120) NOT NULL,
	media_type varchar(30) NOT NULL,
	last_enlightened varchar(30));

CREATE TABLE genre(
	media_id integer REFERENCES media(id) ON DELETE CASCADE,
	genre varchar(70) NOT NULL,
	PRIMARY KEY(media_id, genre));

CREATE TABLE animation(
	media_id integer PRIMARY KEY REFERENCES media(id) ON DELETE CASCADE,
	studio varchar(30),
	season integer NOT NULL,
	episode integer NOT NULL);

CREATE TABLE comic(
	media_id integer PRIMARY KEY REFERENCES media(id) ON DELETE CASCADE,
	author varchar(30),
	chapters_read varchar(30) NOT NULL,
	last_read varchar(30),
	chapters_released varchar(30) NOT NULL,
	oneshot boolean);

CREATE TABLE book(
	media_id integer PRIMARY KEY REFERENCES media(id) ON DELETE CASCADE,
	author varchar(30),
	latest_volume_read varchar(30) NOT NULL,
	volumes_released varchar(30) NOT NULL);

CREATE TABLE show(
	media_id integer PRIMARY KEY REFERENCES media(id) ON DELETE CASCADE,
	watched_on varchar(120) NOT NULL,
	season integer NOT NULL,
	episode integer NOT NULL);

CREATE TABLE review(
	id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	media_id integer REFERENCES media(id) ON DELETE RESTRICT,
	body text NOT NULL,
	reviewed_at date NOT NULL DEFAULT CURRENT_DATE);
	





	
	
			